export const GET_USER = 'get_user'
export const DISPLAY = 'display'
export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const SOCKET_MESSAGE = 'socket_message'
export const SOCKET_CONNECTED = 'socket_connected'
